<img src="https://drive.google.com/uc?id=1EOzaynFEkpMjE-PWPqllAYWRScW-2YQ0">

<br>

<hr>

<br>

<center>

<h1> Avisek Gupta </h1>

<h1> Indian Statistical Institute, Kolkata </h1>

</center>

<br>

<hr>

<br>

<br>

<hr>

<br>

<center>

<h1> Tutorial 1: Working with Tensors in PyTorch </h1>

</center>

<br>

<hr>

<br>


In [1]:
import torch

In [2]:
print(torch.__version__)

1.8.1+cu101


In [3]:
print(torch.cuda.is_available())

False


<hr>

<br>

<h2> 1. Different ways of intitializing tensors - </h2>


In [4]:
# Initialize an empty tensor

x = torch.empty(5, 3)
print(x)


tensor([[3.8515e-28, 3.0691e-41, 3.3631e-44],
        [0.0000e+00,        nan, 2.6908e+20],
        [1.1578e+27, 1.1362e+30, 7.1547e+22],
        [4.5828e+30, 1.2121e+04, 7.1846e+22],
        [9.2198e-39, 7.0374e+22, 1.0128e-28]])


In [5]:
# Initialize a zero tensor

x = torch.zeros(5, 3, dtype=torch.long)
print(x)


tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [6]:
# Initialize a random tensor

x = torch.rand(5, 3)
print(x)


tensor([[0.4805, 0.5674, 0.6114],
        [0.3374, 0.2846, 0.4141],
        [0.5330, 0.1123, 0.6748],
        [0.9518, 0.6749, 0.7500],
        [0.6629, 0.1617, 0.6080]])


In [7]:
# Initialize a specific tensor

x = torch.tensor([5.5, 3])
print(x)


tensor([5.5000, 3.0000])


In [8]:
# Create a separate copy an existing tensor using clone

x = torch.zeros(2, 3, dtype=torch.long)
y = x.clone()
x = x + 1
print(x)
print(y)


tensor([[1, 1, 1],
        [1, 1, 1]])
tensor([[0, 0, 0],
        [0, 0, 0]])


In [9]:
# Initialize with previous tensor's attributes

x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)


tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.5087,  0.8621, -0.7676],
        [ 0.9275,  1.4946, -0.2577],
        [-0.4062, -0.6010, -1.6853],
        [ 0.3337, -1.1937,  0.6211],
        [ 0.4633,  0.1690,  2.7207]])


<hr>

<br>

<h2> 2. Different ways of adding two vectors - </h2>


In [10]:
y = torch.rand(5, 3)

print(x + y)

print(torch.add(x, y))

result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

y.add_(x)
print(y)


tensor([[ 0.2997,  1.2734, -0.6246],
        [ 1.1735,  2.1222,  0.6334],
        [-0.0203,  0.0986, -1.4308],
        [ 1.2026, -0.2370,  0.9991],
        [ 0.5754,  0.5744,  3.2674]])
tensor([[ 0.2997,  1.2734, -0.6246],
        [ 1.1735,  2.1222,  0.6334],
        [-0.0203,  0.0986, -1.4308],
        [ 1.2026, -0.2370,  0.9991],
        [ 0.5754,  0.5744,  3.2674]])
tensor([[ 0.2997,  1.2734, -0.6246],
        [ 1.1735,  2.1222,  0.6334],
        [-0.0203,  0.0986, -1.4308],
        [ 1.2026, -0.2370,  0.9991],
        [ 0.5754,  0.5744,  3.2674]])
tensor([[ 0.2997,  1.2734, -0.6246],
        [ 1.1735,  2.1222,  0.6334],
        [-0.0203,  0.0986, -1.4308],
        [ 1.2026, -0.2370,  0.9991],
        [ 0.5754,  0.5744,  3.2674]])


<hr>

<br>

<h2> 3. General Tensor operations - </h2>

In [11]:
# Get tensor size

print(x.size())

print(x.size(0), x.size()[1])


torch.Size([5, 3])
5 3


In [12]:
# Get slice of a tensor

print(x[:, 1])


tensor([ 0.8621,  1.4946, -0.6010, -1.1937,  0.1690])


In [13]:
# Resize a tensor (i.e., change the view)

x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())


torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [14]:
# Get a single scalar from a tensor

x = torch.randn(1)
print(x)
print(x.item())


tensor([0.0680])
0.06802535057067871


<hr>

<br>

<h2> 4. Converting Tensors from Torch to Numpy Arrays, and back - </h2>


In [15]:
a = torch.ones(5)
print(a)

# Converting to a numpy array (uses the same memory location if on CPU)
b = a.numpy()
print(b)

a.add_(1)
print(a)
print(b)


tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [16]:
import numpy as np

a = np.ones(5)
b = torch.from_numpy(a)  # Uses the same memory location (if on CPU)
np.add(a, 1, out=a)

print(a)
print(b)


[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


<hr>

<br>

<h2> 5. Running code on the CUDA device - </h2>

In [1]:
import torch
print(torch.__version__)
print(torch.cuda.is_available())


1.8.1+cu101
True


In [2]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    x = torch.rand(5, 3)
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)
    z = x + y
    print(z)
    print(z.to("cpu"))
    

tensor([[1.6030, 1.0554, 1.8243],
        [1.6876, 1.5408, 1.2670],
        [1.8411, 1.4868, 1.9681],
        [1.8510, 1.2308, 1.2255],
        [1.7303, 1.8777, 1.6621]], device='cuda:0')
tensor([[1.6030, 1.0554, 1.8243],
        [1.6876, 1.5408, 1.2670],
        [1.8411, 1.4868, 1.9681],
        [1.8510, 1.2308, 1.2255],
        [1.7303, 1.8777, 1.6621]])


In [3]:
# If available, run on the GPU, else run on the CPU
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
y = torch.ones_like(x, device=device)
x = x.to(device)
z = x + y
print(z)


tensor([[1.6030, 1.0554, 1.8243],
        [1.6876, 1.5408, 1.2670],
        [1.8411, 1.4868, 1.9681],
        [1.8510, 1.2308, 1.2255],
        [1.7303, 1.8777, 1.6621]], device='cuda:0')


<hr>

<br>

<h2> Recap: </h2>

<h2> 1. Different ways of intitializing tensors </h2>

<h2> 2. Different ways of performing an operation between two vectors </h2>

<h2> 3. General Tensor operations </h2>

<h2> 4. Converting Tensors from Torch to Numpy Arrays, and back </h2>

<h2> 5. Running PyTorch on the CUDA device </h2>

<br>

<hr>

<br>

<h2> References: </h2>

<ul>
    <br>
    <li> <h2> <a href="https://pytorch.org/tutorials/beginner/basics/tensorqs_tutorial.html"> PyTorch Tutorial on Tensors </a> </h2> </li>
    <br>
    <li> <h2> <a href="https://pytorch.org/tutorials/"> The PyTorch Documentation </a> </h2> </li>
</ul>

<br>